regions: li_hiv_call3/inputs/regions.bed
ref_file: li_hiv_call3/inputs/hiv_hxb2.fa
viquas_dir: ViQuaS1.3
params:
  prep: [pear]
  caller: lofreq
  lofreq:
    fn_highfreq_thresh: 5.0
    fp_thresh: 2.5
    sb_thresh: 600
  freebayes:
    min_alt_fraction: 0.0001
    haplotype_length: 0
    min_count: 6
  pear:
    quality_thresh: 3
    min_overlap: 50
    min_trim_length: 50
    max_uncalled_base: 1
  bfc:
    min_kmer_cov: 5
  viquas:
    o: 5
    r: 0.6
  validation:
    vcf_prep_method: pileup
control_vcf: li_hiv_call3/inputs/controls-freqs.vcf
controls:
  IN: li_hiv_call3/inputs/IN-control.fa
  PRO-RT: li_hiv_call3/inputs/PRO-RT-control.fa
  V3-Loop: li_hiv_call3/inputs/V3_Loop-control.fa

#HIVHXB2CG	2064	2700	PRO-RT_1
#HIVHXB2CG	2700	3250	PRO-RT_2
#HIVHXB2CG	3250	3800	PRO-RT_3
#HIVHXB2CG	4312	4800	IN_1
#HIVHXB2CG	4800	5189	IN_2
#
#HIVHXB2CG	2064	3800	PRO-RT
#HIVHXB2CG	4312	5189	IN
#HIVHXB2CG	6906	7314	V3-Loop